AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple Flask app with AWS Lambda and API Gateway
Globals:
  Function:
    Timeout: 10
Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://clam-bucket/d7191f9da1c7a2f788c2a41e815246fe
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      SamResourceId: FlaskFunction
Outputs:
  ApiURL:
    Description: API Gateway endpoint URL for Prod stage for Flask function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
